# Generated by Django 2.0 on 2018-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0010_auto_20180418_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='O campo CPF é obriagatório.', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='O campo Email é obrigatório.', max_length=60, unique=True, verbose_name='Email'),
        ),
    ]
