# Generated by Django 2.0.1 on 2018-05-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0012_auto_20180501_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opiniao',
            old_name='contras',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='opiniao',
            old_name='pros',
            new_name='pro',
        ),
    ]
