# Generated by Django 2.0.1 on 2018-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0013_auto_20180521_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='codigo_exemplo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='contra',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='pro',
            field=models.CharField(max_length=800),
        ),
    ]
