# Generated by Django 2.0.1 on 2018-05-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0014_auto_20180521_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
