# Generated by Django 2.0 on 2018-05-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0016_comentario_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='wofapp.Linguagem'),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helloworlds', to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='link',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinioes', to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='versao',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='wofapp.Framework'),
        ),
    ]
