# Generated by Django 2.0.1 on 2018-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0017_auto_20180522_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versao',
            old_name='descricao',
            new_name='funcionalidades',
        ),
    ]
