# Generated by Django 2.0.1 on 2018-06-11 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0022_auto_20180528_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='contra',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='versao',
            name='funcionalidades',
        ),
        migrations.AddField(
            model_name='comentario',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helloworld',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='helloworld',
            name='versao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='link',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opiniao',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='eh_favoravel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='texto',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opiniao',
            name='versao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='wofapp.Framework'),
        ),
        migrations.AddField(
            model_name='versao',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='funcionalidades',
            name='denuncias',
            field=models.ManyToManyField(blank=True, to='wofapp.Denuncia'),
        ),
        migrations.AddField(
            model_name='funcionalidades',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionalidades', to='wofapp.Framework'),
        ),
        migrations.AddField(
            model_name='funcionalidades',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionalidades',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
        ),
    ]
