# Generated by Django 2.0 on 2018-04-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0005_auto_20180410_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_activeUser',
            field=models.BooleanField(default=True),
        ),
    ]
