# Generated by Django 2.0 on 2018-04-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0008_auto_20180418_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_Cadastro',
            new_name='data_cadastro',
        ),
    ]
