# Generated by Django 2.0 on 2018-05-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0011_auto_20180501_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
