# Generated by Django 2.0.1 on 2018-05-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0015_comentario_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='respostas',
            field=models.ManyToManyField(related_name='_comentario_respostas_+', to='wofapp.Comentario'),
        ),
    ]
