# Generated by Django 2.0.1 on 2018-08-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0023_auto_20180611_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='funcionalidades',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='helloworld',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='link',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='denuncias',
        ),
        migrations.RemoveField(
            model_name='versao',
            name='denuncias',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='comentario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='funcionalidades',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Funcionalidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='helloworld',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Helloworld'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='versao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
            preserve_default=False,
        ),
    ]
