# Generated by Django 2.0.1 on 2019-04-27 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0024_auto_20180810_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionalidades',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='funcionalidades',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='funcionalidades',
            name='versao',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='motivo_denuncia',
            new_name='motivo',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='usuario',
            new_name='quem_denunciou',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='path',
            new_name='caminho',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='administrador',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_activeUser',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='primeiro_nome',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='ultimo_nome',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='funcionalidades',
        ),
        migrations.RemoveField(
            model_name='helloworld',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='favoritos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Comentario'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Framework'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='linguagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Linguagem'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='opiniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Opiniao'),
        ),
        migrations.AddField(
            model_name='framework',
            name='favoritado_por',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='framework',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linguagem',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='helloworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Helloworld'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Link'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='versao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='linguagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Linguagem'),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='versao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
        ),
        migrations.AlterField(
            model_name='link',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='versao',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='versao',
            name='numero',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Funcionalidades',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.AddField(
            model_name='funcionalidade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionalidade',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='funcionalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Funcionalidade'),
        ),
    ]
