# Generated by Django 2.0.1 on 2019-05-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0025_auto_20190427_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wofapp.Versao'),
        ),
    ]
