# Generated by Django 2.0.1 on 2019-05-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0026_auto_20190511_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='funcionalidade',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='helloworld',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='link',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='versao',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resolvida',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respostas',
        ),
        migrations.AddField(
            model_name='comentario',
            name='respostas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wofapp.Comentario'),
        ),
    ]
