# Generated by Django 2.0.1 on 2019-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0027_auto_20190526_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='formacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profissao',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
