# Generated by Django 2.0.1 on 2019-05-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0028_auto_20190526_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.CharField(max_length=1000),
        ),
    ]
