# Generated by Django 2.0.1 on 2019-06-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wofapp', '0029_auto_20190528_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='Comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wofapp.Comentario'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wofapp.Framework'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='linguagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wofapp.Linguagem'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='opiniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wofapp.Opiniao'),
        ),
    ]
